### ISSUE TITLE
ImageUtils.getScreenOrientation is not supported in older devices and causes crash

### ISSUE THREAD

**Issue by MohammedZ666** [intel-isl/OpenBot#206]
The following method was updated [in this commit](https://github.com/intel-isl/OpenBot/commit/7e6b220f0988746f6ebdbdaea5a585e29b86f7b0?branch=7e6b220f0988746f6ebdbdaea5a585e29b86f7b0&diff=split) to remove the depreciated call `activity.getWindowManager().getDefaultDisplay().getRotation()`  Unfortunately this crashes my device which has API 21. The call  `activity.getDisplay().getRotation()` requires API level 30:
```
public static int getScreenOrientation(Activity activity) {
    switch (activity.getDisplay().getRotation()) {
      case Surface.ROTATION_270:
        return 270;
      case Surface.ROTATION_180:
        return 180;
      case Surface.ROTATION_90:
        return 90;
      case Surface.ROTATION_0:
      default:
        return 0;
    }
  }
```
Can I replace this method with the following one?
```
public static int getScreenOrientation(Activity activity) {
    int rotation = Build.VERSION.SDK_INT >= Build.VERSION_CODES.R?
             activity.getDisplay().getRotation() : activity.getWindowManager().getDefaultDisplay().getRotation();
    switch (rotation) {
        case Surface.ROTATION_270:
          return 270;
        case Surface.ROTATION_180:
          return 180;
        case Surface.ROTATION_90:
          return 90;
        case Surface.ROTATION_0:
        default:
          return 0;

    }
  }
```
**Adding the above call fixes my problem.**

This is my logcat:
```
07-21 22:27:48.332 29430-29430/org.openbot E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.openbot, PID: 29430
    java.lang.NoSuchMethodError: No virtual method getDisplay()Landroid/view/Display; in class Landroid/app/Activity; or its super classes (declaration of 'android.app.Activity' appears in /system/framework/framework.jar)
        at org.openbot.env.ImageUtils.getScreenOrientation(ImageUtils.java:228)
        at org.openbot.common.CameraFragment.bindCameraUseCases(CameraFragment.java:102)
        at org.openbot.common.CameraFragment.setAnalyserResolution(CameraFragment.java:188)
        at org.openbot.autopilot.AutopilotFragment.onViewCreated(AutopilotFragment.java:116)
        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2987)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2106)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:7223)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```
**This way older devices like mine may be supported. Thanks!**

**Comment by thias15** [comment]
Please follow the [contribution guidelines](https://github.com/intel-isl/OpenBot/blob/master/CONTRIBUTING.md) to open a PR. You can then link this issue to it. Thank you very much!

**Comment by MohammedZ666** [comment]
Thanks!
